Fediseer/FediseerGUI

src/app/glossary/pages/glossary/glossary.component.html
=> Feat: Add links to official home page of Fediseer and a blog post

src/app/action-log/pages/action-log/action-log.component.html, src/app/response/action-log.response.ts
=> Fix: Display guarantees in action log

src/app/auth/pages/claim-instance/claim-instance.component.html, src/app/auth/pages/claim-instance/claim-instance.component.ts, src/app/services/fediseer-api.service.ts, src/app/types/private-message-proxy.ts
=> Feat: Add support for account proxy when claiming instance

src/app/guarantees/pages/my-guarantees/my-guarantees.component.html, src/app/guarantees/pages/my-guarantees/my-guarantees.component.ts
=> Feat: Revoke own guarantor

src/app/action-log/pages/action-log/action-log.component.ts
=> Fix: Correctly work with null values in filter form

src/app/synchronization/components/filter-form/filter-form.component.ts
=> Fix: Correctly populate ignored instances on sync page

src/app/synchronization/components/filter-form/filter-form.component.html, src/app/synchronization/components/filter-form/filter-form.component.ts
=> Feat: Ignore endorsed instances when synchronizing

src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts, src/app/auth/pages/login/login.component.ts, src/app/services/database.service.ts, src/app/shared/shared.module.ts, src/styles.scss
=> Feat: Add support for multiple accounts

src/app/endorsements/pages/edit-endorsement-reasons/edit-endorsement-reasons.component.html, src/app/endorsements/pages/endorse-instance/endorse-instance.component.html, src/app/glossary/pages/glossary/glossary.component.html, src/assets/i18n/en.json, src/assets/i18n/pt.json
=> Feat: Add link to glossary for guarantee restricted info

src/app/censures/pages/my-censures/my-censures.component.html, src/app/endorsements/pages/my-endorsements/my-endorsements.component.html, src/app/guarantees/pages/my-guarantees/my-guarantees.component.html, src/app/hesitations/pages/my-hesitations/my-hesitations.component.html, src/app/instances/pages/instance-detail/instance-detail.component.html, src/app/instances/pages/whitelisted-instances/whitelisted-instances.component.html, src/app/response/normalized-instance-detail.response.ts
=> Feat: Show instance status on more relevant pages

src/app/services/mastodon-api.service.ts, src/app/services/mastodon-link-parser.service.ts
=> Fix: Use pagination when fetching Mastodon blocks

src/app/synchronization/components/filter-form/filter-form.component.html, src/app/synchronization/components/filter-form/filter-form.component.ts
=> Chore: Add clarifications for synchronization

src/app/endorsements/pages/endorse-instance/endorse-instance.component.ts, src/app/instances/pages/instance-detail/instance-detail.component.html, src/app/instances/pages/instance-detail/instance-detail.component.ts, src/app/shared/components/instance-move-to-list/instance-move-to-list.component.html, src/app/shared/components/instance-move-to-list/instance-move-to-list.component.ts, src/assets/i18n/en.json
=> Feat: Add actions to instance detail

src/app/synchronization/pages/synchronize-lemmy/synchronize-lemmy.component.html, src/app/synchronization/pages/synchronize-mastodon/synchronize-mastodon.component.html, src/app/synchronization/pages/synchronize-mastodon/synchronize-mastodon.component.ts
=> Feat: Add synchronization from Mastodon to Fediseer

src/app/endorsements/pages/my-endorsements/my-endorsements.component.ts, src/app/instances/pages/instance-detail/instance-detail.component.ts, src/app/services/cached-fediseer-api.service.ts
=> Feat: Add some more cached methods

src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/services/database.service.ts, src/app/shared/pipes/language-name.pipe.ts, src/app/shared/shared.module.ts, src/app/transloco-root.module.ts, src/assets/i18n/cs.json, src/assets/i18n/en.json
=> Feat: Add language selector

src/app/action-log/pages/action-log/action-log.component.ts, src/app/instances/pages/censured-instances/censured-instances.component.ts, src/app/instances/pages/hesitated-instances/hesitated-instances.component.ts, src/app/instances/pages/safelisted-instances/safelisted-instances.component.html, src/app/instances/pages/safelisted-instances/safelisted-instances.component.ts, src/app/services/cached-fediseer-api.service.ts, src/app/services/fediseer-api.service.ts, src/app/synchronization/components/filter-form/filter-form.component.ts
=> Feat: Add real pagination for safelist

src/app/censures/pages/censure-instance/censure-instance.component.ts, src/app/censures/pages/edit-censure-reasons/edit-censure-reasons.component.ts, src/app/censures/pages/my-censures/my-censures.component.ts, src/app/guarantees/pages/guarantee-instance/guarantee-instance.component.ts, src/app/hesitations/pages/hesitate-on-instance/hesitate-on-instance.component.ts, src/app/instances/pages/censured-instances/censured-instances.component.html, src/app/instances/pages/censured-instances/censured-instances.component.ts, src/app/instances/pages/instance-detail/instance-detail.component.ts, src/app/instances/pages/suspicious-instances/suspicious-instances.component.ts, src/app/services/cached-fediseer-api.service.ts, src/app/services/fediseer-api.service.ts, src/app/shared/components/instance-move-to-list/instance-move-to-list.component.ts, src/app/synchronization/components/filter-form/filter-form.component.ts, src/app/synchronization/pages/synchronize-lemmy/synchronize-lemmy.component.ts, src/app/synchronization/pages/synchronize-mastodon/synchronize-mastodon.component.ts
=> Feat: Add pagination to censures

src/app/app.component.html
=> Fix: Language color for light theme

src/app/app.component.html, src/app/app.component.ts, src/app/shared/pipes/keys.pipe.ts, src/app/shared/shared.module.ts, src/assets/i18n/en.json
=> Add instance search

src/app/app.component.html, src/app/rebuttals/pages/list-rebuttals/list-rebuttals.component.html, src/app/rebuttals/pages/list-rebuttals/list-rebuttals.component.scss, src/app/rebuttals/pages/list-rebuttals/list-rebuttals.component.ts, src/app/rebuttals/rebuttals.module.ts, src/app/services/api-response-helper.service.ts, src/assets/i18n/en.json
=> Feat: Add list of rebuttals
